### ISSUE TITLE
"Customize this page" sides

### ISSUE THREAD

**Issue by prokopsimek** [HonzaStefanik/spring-starter-buttercms#5]
"Customize this page" and "ButterCMS is your content backend" are the same type but switched position of image and text. I guess that it should be same order of img + text (img on left side and text on the right side)

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5487217/164290292-4eb01013-f0c2-47c9-96b2-f6533581415c.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5487217/164290360-31a96770-24c9-453a-ae1f-6ca6358547e7.png">

**Comment by HonzaStefanik** [comment]
I thought that was intentional as this is how it was done in the prepared HTML samples as well as in other starter projets, [react-starter](https://nextjs-starter-buttercms.vercel.app) for example

**Comment by prokopsimek** [comment]
I see same positions in React demo - https://nextjs-starter-buttercms.vercel.app/

- "ButterCMS is your content backend" - image left, text right
- "Customize this page" = image **left**, text **right**

Java:
- "ButterCMS is your content backend" - image left, text right
- "Customize this page" = image **right**, text **left**
- https://bcms-java-test2.herokuapp.com/

Both sections should be the same - as in the first demo - both images on the left side and text on the right side.
